# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reactiongameui.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setAutoFillBackground(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Main = QtWidgets.QFrame(Form)
        self.Main.setAutoFillBackground(False)
        self.Main.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Main.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Main.setObjectName("Main")
        self.Button2 = QtWidgets.QPushButton(self.Main)
        self.Button2.setGeometry(QtCore.QRect(675, 555, 101, 23))
        self.Button2.setObjectName("Button2")
        self.BarLabel3 = QtWidgets.QLabel(self.Main)
        self.BarLabel3.setGeometry(QtCore.QRect(10, 5, 270, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        self.BarLabel3.setFont(font)
        self.BarLabel3.setAutoFillBackground(True)
        self.BarLabel3.setAlignment(QtCore.Qt.AlignCenter)
        self.BarLabel3.setObjectName("BarLabel3")
        self.Button1 = QtWidgets.QPushButton(self.Main)
        self.Button1.setGeometry(QtCore.QRect(570, 555, 101, 23))
        self.Button1.setObjectName("Button1")
        self.BarLabel1 = QtWidgets.QLabel(self.Main)
        self.BarLabel1.setGeometry(QtCore.QRect(500, 5, 270, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        self.BarLabel1.setFont(font)
        self.BarLabel1.setAutoFillBackground(True)
        self.BarLabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.BarLabel1.setObjectName("BarLabel1")
        self.BarLabel2 = QtWidgets.QLabel(self.Main)
        self.BarLabel2.setGeometry(QtCore.QRect(270, 5, 270, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        self.BarLabel2.setFont(font)
        self.BarLabel2.setAutoFillBackground(True)
        self.BarLabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.BarLabel2.setObjectName("BarLabel2")
        self.BackLabel = QtWidgets.QLabel(self.Main)
        self.BackLabel.setGeometry(QtCore.QRect(9, 4, 762, 33))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        self.BackLabel.setFont(font)
        self.BackLabel.setAutoFillBackground(True)
        self.BackLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BackLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.BackLabel.setText("")
        self.BackLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.BackLabel.setObjectName("BackLabel")
        self.QF2 = QtWidgets.QFrame(self.Main)
        self.QF2.setGeometry(QtCore.QRect(60, 181, 170, 62))
        self.QF2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.QF2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.QF2.setObjectName("QF2")
        self.label_5 = QtWidgets.QLabel(self.QF2)
        self.label_5.setGeometry(QtCore.QRect(0, 31, 125, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAutoFillBackground(True)
        self.label_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.QF2)
        self.label_6.setGeometry(QtCore.QRect(124, 31, 47, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setAutoFillBackground(True)
        self.label_6.setFrameShape(QtWidgets.QFrame.Box)
        self.label_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.QF2)
        self.label_7.setGeometry(QtCore.QRect(124, 0, 47, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setAutoFillBackground(True)
        self.label_7.setFrameShape(QtWidgets.QFrame.Box)
        self.label_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.QF2)
        self.label_8.setGeometry(QtCore.QRect(0, 0, 125, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setAutoFillBackground(True)
        self.label_8.setFrameShape(QtWidgets.QFrame.Box)
        self.label_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_8.raise_()
        self.label_7.raise_()
        self.QF1 = QtWidgets.QFrame(self.Main)
        self.QF1.setGeometry(QtCore.QRect(60, 60, 170, 62))
        self.QF1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.QF1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.QF1.setObjectName("QF1")
        self.label_9 = QtWidgets.QLabel(self.QF1)
        self.label_9.setGeometry(QtCore.QRect(0, 31, 125, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setAutoFillBackground(True)
        self.label_9.setFrameShape(QtWidgets.QFrame.Box)
        self.label_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.QF1)
        self.label_10.setGeometry(QtCore.QRect(124, 31, 47, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setAutoFillBackground(True)
        self.label_10.setFrameShape(QtWidgets.QFrame.Box)
        self.label_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.QF1)
        self.label_11.setGeometry(QtCore.QRect(124, 0, 47, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setAutoFillBackground(True)
        self.label_11.setFrameShape(QtWidgets.QFrame.Box)
        self.label_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.QF1)
        self.label_12.setGeometry(QtCore.QRect(0, 0, 125, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setAutoFillBackground(True)
        self.label_12.setFrameShape(QtWidgets.QFrame.Box)
        self.label_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_12.raise_()
        self.label_11.raise_()
        self.QF3 = QtWidgets.QFrame(self.Main)
        self.QF3.setGeometry(QtCore.QRect(60, 301, 170, 62))
        self.QF3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.QF3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.QF3.setObjectName("QF3")
        self.label_13 = QtWidgets.QLabel(self.QF3)
        self.label_13.setGeometry(QtCore.QRect(0, 31, 125, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setAutoFillBackground(True)
        self.label_13.setFrameShape(QtWidgets.QFrame.Box)
        self.label_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.QF3)
        self.label_14.setGeometry(QtCore.QRect(124, 31, 47, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setAutoFillBackground(True)
        self.label_14.setFrameShape(QtWidgets.QFrame.Box)
        self.label_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.QF3)
        self.label_15.setGeometry(QtCore.QRect(124, 0, 47, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setAutoFillBackground(True)
        self.label_15.setFrameShape(QtWidgets.QFrame.Box)
        self.label_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.QF3)
        self.label_16.setGeometry(QtCore.QRect(0, 0, 125, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setAutoFillBackground(True)
        self.label_16.setFrameShape(QtWidgets.QFrame.Box)
        self.label_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_16.raise_()
        self.label_15.raise_()
        self.QF4 = QtWidgets.QFrame(self.Main)
        self.QF4.setGeometry(QtCore.QRect(60, 421, 170, 62))
        self.QF4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.QF4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.QF4.setObjectName("QF4")
        self.label_17 = QtWidgets.QLabel(self.QF4)
        self.label_17.setGeometry(QtCore.QRect(0, 31, 125, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setAutoFillBackground(True)
        self.label_17.setFrameShape(QtWidgets.QFrame.Box)
        self.label_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.QF4)
        self.label_18.setGeometry(QtCore.QRect(124, 31, 47, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setAutoFillBackground(True)
        self.label_18.setFrameShape(QtWidgets.QFrame.Box)
        self.label_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.QF4)
        self.label_19.setGeometry(QtCore.QRect(124, 0, 47, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setAutoFillBackground(True)
        self.label_19.setFrameShape(QtWidgets.QFrame.Box)
        self.label_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.QF4)
        self.label_20.setGeometry(QtCore.QRect(0, 0, 125, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setAutoFillBackground(True)
        self.label_20.setFrameShape(QtWidgets.QFrame.Box)
        self.label_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_20.raise_()
        self.label_19.raise_()
        self.SF1 = QtWidgets.QFrame(self.Main)
        self.SF1.setGeometry(QtCore.QRect(331, 120, 170, 62))
        self.SF1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SF1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SF1.setObjectName("SF1")
        self.label_21 = QtWidgets.QLabel(self.SF1)
        self.label_21.setGeometry(QtCore.QRect(0, 31, 125, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setAutoFillBackground(True)
        self.label_21.setFrameShape(QtWidgets.QFrame.Box)
        self.label_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.SF1)
        self.label_22.setGeometry(QtCore.QRect(124, 31, 47, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setAutoFillBackground(True)
        self.label_22.setFrameShape(QtWidgets.QFrame.Box)
        self.label_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.SF1)
        self.label_23.setGeometry(QtCore.QRect(124, 0, 47, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setAutoFillBackground(True)
        self.label_23.setFrameShape(QtWidgets.QFrame.Box)
        self.label_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.SF1)
        self.label_24.setGeometry(QtCore.QRect(0, 0, 125, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setAutoFillBackground(True)
        self.label_24.setFrameShape(QtWidgets.QFrame.Box)
        self.label_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.label_21.raise_()
        self.label_22.raise_()
        self.label_24.raise_()
        self.label_23.raise_()
        self.SF2 = QtWidgets.QFrame(self.Main)
        self.SF2.setGeometry(QtCore.QRect(331, 360, 170, 62))
        self.SF2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SF2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SF2.setObjectName("SF2")
        self.label_25 = QtWidgets.QLabel(self.SF2)
        self.label_25.setGeometry(QtCore.QRect(0, 31, 125, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setAutoFillBackground(True)
        self.label_25.setFrameShape(QtWidgets.QFrame.Box)
        self.label_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.SF2)
        self.label_26.setGeometry(QtCore.QRect(124, 31, 47, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.label_26.setFont(font)
        self.label_26.setAutoFillBackground(True)
        self.label_26.setFrameShape(QtWidgets.QFrame.Box)
        self.label_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.SF2)
        self.label_27.setGeometry(QtCore.QRect(124, 0, 47, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setAutoFillBackground(True)
        self.label_27.setFrameShape(QtWidgets.QFrame.Box)
        self.label_27.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.SF2)
        self.label_28.setGeometry(QtCore.QRect(0, 0, 125, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setAutoFillBackground(True)
        self.label_28.setFrameShape(QtWidgets.QFrame.Box)
        self.label_28.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.label = QtWidgets.QLabel(self.Main)
        self.label.setGeometry(QtCore.QRect(331, 340, 171, 16))
        self.label.setObjectName("label")
        self.FinalMatchFrame = QtWidgets.QFrame(self.Main)
        self.FinalMatchFrame.setGeometry(QtCore.QRect(581, 240, 170, 62))
        self.FinalMatchFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FinalMatchFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FinalMatchFrame.setObjectName("FinalMatchFrame")
        self.label_29 = QtWidgets.QLabel(self.FinalMatchFrame)
        self.label_29.setGeometry(QtCore.QRect(0, 31, 125, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.label_29.setFont(font)
        self.label_29.setAutoFillBackground(True)
        self.label_29.setFrameShape(QtWidgets.QFrame.Box)
        self.label_29.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.FinalMatchFrame)
        self.label_30.setGeometry(QtCore.QRect(124, 31, 47, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.label_30.setFont(font)
        self.label_30.setAutoFillBackground(True)
        self.label_30.setFrameShape(QtWidgets.QFrame.Box)
        self.label_30.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.FinalMatchFrame)
        self.label_31.setGeometry(QtCore.QRect(124, 0, 47, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.label_31.setFont(font)
        self.label_31.setAutoFillBackground(True)
        self.label_31.setFrameShape(QtWidgets.QFrame.Box)
        self.label_31.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.FinalMatchFrame)
        self.label_32.setGeometry(QtCore.QRect(0, 0, 125, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.label_32.setFont(font)
        self.label_32.setAutoFillBackground(True)
        self.label_32.setFrameShape(QtWidgets.QFrame.Box)
        self.label_32.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.ChampionsFrame = QtWidgets.QFrame(self.Main)
        self.ChampionsFrame.setGeometry(QtCore.QRect(581, 451, 170, 60))
        self.ChampionsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ChampionsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ChampionsFrame.setObjectName("ChampionsFrame")
        self.label_33 = QtWidgets.QLabel(self.ChampionsFrame)
        self.label_33.setGeometry(QtCore.QRect(0, 30, 170, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.label_33.setFont(font)
        self.label_33.setAutoFillBackground(True)
        self.label_33.setFrameShape(QtWidgets.QFrame.Box)
        self.label_33.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.label_36 = QtWidgets.QLabel(self.ChampionsFrame)
        self.label_36.setGeometry(QtCore.QRect(0, 0, 170, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.label_36.setFont(font)
        self.label_36.setAutoFillBackground(True)
        self.label_36.setFrameShape(QtWidgets.QFrame.Box)
        self.label_36.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.frame_QF1toSF1 = QtWidgets.QFrame(self.Main)
        self.frame_QF1toSF1.setGeometry(QtCore.QRect(230, 70, 101, 81))
        self.frame_QF1toSF1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_QF1toSF1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_QF1toSF1.setObjectName("frame_QF1toSF1")
        self.line = QtWidgets.QFrame(self.frame_QF1toSF1)
        self.line.setGeometry(QtCore.QRect(0, 13, 51, 16))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.line_3 = QtWidgets.QFrame(self.frame_QF1toSF1)
        self.line_3.setGeometry(QtCore.QRect(50, 20, 3, 46))
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setLineWidth(2)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setObjectName("line_3")
        self.line_6 = QtWidgets.QFrame(self.frame_QF1toSF1)
        self.line_6.setGeometry(QtCore.QRect(51, 56, 52, 20))
        self.line_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_6.setLineWidth(2)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setObjectName("line_6")
        self.frame_QF3toSF2 = QtWidgets.QFrame(self.Main)
        self.frame_QF3toSF2.setGeometry(QtCore.QRect(230, 310, 101, 81))
        self.frame_QF3toSF2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_QF3toSF2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_QF3toSF2.setObjectName("frame_QF3toSF2")
        self.line_2 = QtWidgets.QFrame(self.frame_QF3toSF2)
        self.line_2.setGeometry(QtCore.QRect(0, 13, 51, 16))
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.line_7 = QtWidgets.QFrame(self.frame_QF3toSF2)
        self.line_7.setGeometry(QtCore.QRect(50, 20, 3, 46))
        self.line_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_7.setLineWidth(2)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.frame_QF3toSF2)
        self.line_8.setGeometry(QtCore.QRect(51, 56, 52, 20))
        self.line_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_8.setLineWidth(2)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setObjectName("line_8")
        self.frame_QF4toSF2 = QtWidgets.QFrame(self.Main)
        self.frame_QF4toSF2.setGeometry(QtCore.QRect(230, 387, 101, 81))
        self.frame_QF4toSF2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_QF4toSF2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_QF4toSF2.setObjectName("frame_QF4toSF2")
        self.line_9 = QtWidgets.QFrame(self.frame_QF4toSF2)
        self.line_9.setGeometry(QtCore.QRect(0, 56, 51, 16))
        self.line_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_9.setLineWidth(2)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.frame_QF4toSF2)
        self.line_10.setGeometry(QtCore.QRect(50, 19, 3, 46))
        self.line_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_10.setLineWidth(2)
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(self.frame_QF4toSF2)
        self.line_11.setGeometry(QtCore.QRect(51, 10, 52, 20))
        self.line_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_11.setLineWidth(2)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setObjectName("line_11")
        self.frame_QF2toSF1 = QtWidgets.QFrame(self.Main)
        self.frame_QF2toSF1.setGeometry(QtCore.QRect(230, 147, 101, 81))
        self.frame_QF2toSF1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_QF2toSF1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_QF2toSF1.setObjectName("frame_QF2toSF1")
        self.line_12 = QtWidgets.QFrame(self.frame_QF2toSF1)
        self.line_12.setGeometry(QtCore.QRect(0, 56, 51, 16))
        self.line_12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_12.setLineWidth(2)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setObjectName("line_12")
        self.line_13 = QtWidgets.QFrame(self.frame_QF2toSF1)
        self.line_13.setGeometry(QtCore.QRect(50, 19, 3, 46))
        self.line_13.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_13.setLineWidth(2)
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setObjectName("line_13")
        self.line_14 = QtWidgets.QFrame(self.frame_QF2toSF1)
        self.line_14.setGeometry(QtCore.QRect(51, 10, 52, 20))
        self.line_14.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_14.setLineWidth(2)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setObjectName("line_14")
        self.frame_SF2toF1 = QtWidgets.QFrame(self.Main)
        self.frame_SF2toF1.setGeometry(QtCore.QRect(501, 266, 81, 136))
        self.frame_SF2toF1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_SF2toF1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_SF2toF1.setObjectName("frame_SF2toF1")
        self.line_15 = QtWidgets.QFrame(self.frame_SF2toF1)
        self.line_15.setGeometry(QtCore.QRect(0, 117, 51, 16))
        self.line_15.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_15.setLineWidth(2)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setObjectName("line_15")
        self.line_16 = QtWidgets.QFrame(self.frame_SF2toF1)
        self.line_16.setGeometry(QtCore.QRect(50, 19, 3, 107))
        self.line_16.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_16.setLineWidth(2)
        self.line_16.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_16.setObjectName("line_16")
        self.line_17 = QtWidgets.QFrame(self.frame_SF2toF1)
        self.line_17.setGeometry(QtCore.QRect(51, 10, 33, 20))
        self.line_17.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_17.setLineWidth(2)
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setObjectName("line_17")
        self.frame_SF2toF1_2 = QtWidgets.QFrame(self.Main)
        self.frame_SF2toF1_2.setGeometry(QtCore.QRect(501, 132, 81, 136))
        self.frame_SF2toF1_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_SF2toF1_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_SF2toF1_2.setObjectName("frame_SF2toF1_2")
        self.line_18 = QtWidgets.QFrame(self.frame_SF2toF1_2)
        self.line_18.setGeometry(QtCore.QRect(0, 11, 51, 16))
        self.line_18.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_18.setLineWidth(2)
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setObjectName("line_18")
        self.line_19 = QtWidgets.QFrame(self.frame_SF2toF1_2)
        self.line_19.setGeometry(QtCore.QRect(50, 18, 3, 109))
        self.line_19.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_19.setLineWidth(2)
        self.line_19.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_19.setObjectName("line_19")
        self.line_20 = QtWidgets.QFrame(self.frame_SF2toF1_2)
        self.line_20.setGeometry(QtCore.QRect(51, 116, 33, 20))
        self.line_20.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_20.setLineWidth(2)
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setObjectName("line_20")
        self.BackLabel.raise_()
        self.Button2.raise_()
        self.BarLabel3.raise_()
        self.Button1.raise_()
        self.BarLabel1.raise_()
        self.BarLabel2.raise_()
        self.QF2.raise_()
        self.QF1.raise_()
        self.QF3.raise_()
        self.QF4.raise_()
        self.SF1.raise_()
        self.SF2.raise_()
        self.label.raise_()
        self.FinalMatchFrame.raise_()
        self.ChampionsFrame.raise_()
        self.frame_QF1toSF1.raise_()
        self.frame_QF3toSF2.raise_()
        self.frame_QF4toSF2.raise_()
        self.frame_QF2toSF1.raise_()
        self.frame_SF2toF1.raise_()
        self.frame_SF2toF1_2.raise_()
        self.verticalLayout.addWidget(self.Main)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Button2.setText(_translate("Form", "Quit Tournament"))
        self.BarLabel3.setText(_translate("Form", "Quarter-Finals"))
        self.Button1.setText(_translate("Form", "Play Next Match"))
        self.BarLabel1.setText(_translate("Form", "Final"))
        self.BarLabel2.setText(_translate("Form", "Semi-Finals"))
        self.label_5.setText(_translate("Form", "Player 4"))
        self.label_6.setText(_translate("Form", "0"))
        self.label_7.setText(_translate("Form", "0"))
        self.label_8.setText(_translate("Form", "Player 3"))
        self.label_9.setText(_translate("Form", "Player 2"))
        self.label_10.setText(_translate("Form", "0"))
        self.label_11.setText(_translate("Form", "0"))
        self.label_12.setText(_translate("Form", "Player 1"))
        self.label_13.setText(_translate("Form", "Player 6"))
        self.label_14.setText(_translate("Form", "0"))
        self.label_15.setText(_translate("Form", "0"))
        self.label_16.setText(_translate("Form", "Player 5"))
        self.label_17.setText(_translate("Form", "Player 8"))
        self.label_18.setText(_translate("Form", "0"))
        self.label_19.setText(_translate("Form", "0"))
        self.label_20.setText(_translate("Form", "Player 7"))
        self.label_21.setText(_translate("Form", "QF 2 Winner"))
        self.label_22.setText(_translate("Form", "0"))
        self.label_23.setText(_translate("Form", "0"))
        self.label_24.setText(_translate("Form", "QF 1 Winner"))
        self.label_25.setText(_translate("Form", "QF 4 Winner"))
        self.label_26.setText(_translate("Form", "0"))
        self.label_27.setText(_translate("Form", "0"))
        self.label_28.setText(_translate("Form", "QF 3 Winner"))
        self.label.setText(_translate("Form", "Semi-Final 2"))
        self.label_29.setText(_translate("Form", "SF 2 Winner"))
        self.label_30.setText(_translate("Form", "0"))
        self.label_31.setText(_translate("Form", "0"))
        self.label_32.setText(_translate("Form", "SF 1 Winner"))
        self.label_33.setText(_translate("Form", "Winner\'s Name"))
        self.label_36.setText(_translate("Form", "Champion"))

