from PyQt5 import QtCore, QtGui, QtWidgets

class bracket():
    def __init__(self, Widget):
        self.base_widget = QWidget(Widget)

        self.quit_tournament_button = QPushButton(self.base_widget)
        self.quarter_final_label = QLabel(self.base_widget)
        self.next_match_button = QPushButton(self.base_widget)
        self.final_label = QLabel(self.base_widget)
        self.semi_final_label = QLabel(self.base_widget)
        self.p4_name_label = QLabel(self.base_widget)
        self.p4_score_label = QLabel(self.base_widget)
        self.p3_score_label = QLabel(self.base_widget)
        self.p3_name_label = QLabel(self.base_widget)
        self.p2_name_label = QLabel(self.base_widget)
        self.p2_score_label = QLabel(self.base_widget)
        self.p1_score_label = QLabel(self.base_widget)
        self.p1_name_label = QLabel(self.base_widget)
        self.p6_name_label = QLabel(self.base_widget)
        self.p6_score_label = QLabel(self.base_widget)
        self.p5_score_label = QLabel(self.base_widget)
        self.p5_name_label = QLabel(self.base_widget)
        self.p8_name_label = QLabel(self.base_widget)
        self.p8_score_label = QLabel(self.base_widget)
        self.p7_score_label = QLabel(self.base_widget)
        self.p7_name_label = QLabel(self.base_widget)
        self.qf2_name_label = QLabel(self.base_widget)
        self.qf2_score_label = QLabel(self.base_widget)
        self.qf1_score_label = QLabel(self.base_widget)
        self.qf1_name_label = QLabel(self.base_widget)
        self.qf4_name_label = QLabel(self.base_widget)
        self.qf4_score_label = QLabel(self.base_widget)
        self.qf3_score_label = QLabel(self.base_widget)
        self.qf3_name_label = QLabel(self.base_widget)
        self.sf2_name_label = QLabel(self.base_widget)
        self.sf2_score_label = QLabel(self.base_widget)
        self.sf1_score_label = QLabel(self.base_widget)
        self.sf1_name_label = QLabel(self.base_widget)
        self.champion_name_label = QLabel(self.base_widget)
        self.champion_label = QLabel(self.base_widget)

        self.base_widget.show()

    def setupui(self):
        self.quit_tournament_button.setGeometry(QtCore.QRect(675, 555, 101, 23)
        self.quarter_final_label.setGeometry(QtCore.QRect(10, 5, 270, 31))
        self.next_match_button.setGeometry(QtCore.QRect(570, 555, 101, 23))
        self.final_label.setGeometry(QtCore.QRect(500, 5, 270, 31))
        self.semi_final_label.setGeometry(QtCore.QRect(270, 5, 270, 31))
        self.QF2.setGeometry(QtCore.QRect(60, 181, 170, 62))
        self.BackLabel.setGeometry(QtCore.QRect(9, 4, 762, 33))
        self.p4_score_label.setGeometry(QtCore.QRect(124, 31, 47, 31))
        self.p4_name_label.setGeometry(QtCore.QRect(0, 31, 125, 31))
        self.p3_score_label.setGeometry(QtCore.QRect(124, 0, 47, 31))
        self.p3_name_label.setGeometry(QtCore.QRect(0, 0, 125, 31))
        self.p2_name_label.setGeometry(QtCore.QRect(0, 31, 125, 31))
        self.p2_score_label.setGeometry(QtCore.QRect(124, 31, 47, 31))
        self.p1_score_label.setGeometry(QtCore.QRect(124, 0, 47, 31))
        self.p1_name_label.setGeometry(QtCore.QRect(0, 0, 125, 31))
        self.p6_name_label.setGeometry(QtCore.QRect(0, 31, 125, 31))
        self.p6_score_label.setGeometry(QtCore.QRect(124, 31, 47, 31))
        self.p5_score_label.setGeometry(QtCore.QRect(124, 0, 47, 31))
        self.p5_name_label.setGeometry(QtCore.QRect(0, 0, 125, 31))
        self.QF4.setGeometry(QtCore.QRect(60, 421, 170, 62))
        self.p8_name_label.setGeometry(QtCore.QRect(0, 31, 125, 31))
        self.p8_score_label.setGeometry(QtCore.QRect(124, 31, 47, 31))
        self.p7_score_label.setGeometry(QtCore.QRect(124, 0, 47, 31))
        self.p7_name_label.setGeometry(QtCore.QRect(0, 0, 125, 31))
        self.qf2_name_label.setGeometry(QtCore.QRect(0, 31, 125, 31))
        self.qf2_score_label.setGeometry(QtCore.QRect(124, 31, 47, 31))
        self.qf1_score_label.setGeometry(QtCore.QRect(124, 0, 47, 31))
        self.qf1_name_label.setGeometry(QtCore.QRect(0, 0, 125, 31))
        self.SF2.setGeometry(QtCore.QRect(331, 360, 170, 62))
        self.qf4_name_label.setGeometry(QtCore.QRect(0, 31, 125, 31))
        self.qf4_score_label.setGeometry(QtCore.QRect(124, 31, 47, 31))
        self.qf3_score_label.setGeometry(QtCore.QRect(124, 0, 47, 31))
        self.qf3_name_label.setGeometry(QtCore.QRect(0, 0, 125, 31))
        self.label.setGeometry(QtCore.QRect(331, 340, 171, 16))
        self.sf2_name_label.setGeometry(QtCore.QRect(0, 31, 125, 31))
        self.sf2_score_label.setGeometry(QtCore.QRect(124, 31, 47, 31))
        self.sf1_score_label.setGeometry(QtCore.QRect(124, 0, 47, 31))
        self.sf1_name_label.setGeometry(QtCore.QRect(0, 0, 125, 31))
        self.champion_name_label.setGeometry(QtCore.QRect(0, 30, 170, 31))
        self.champion_label.setGeometry(QtCore.QRect(0, 0, 170, 31))
        
        
